name: Raptor CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  build-linux:
    name: Raptor CI LLVM ${{ matrix.llvm }} ${{ matrix.build }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        llvm: ["20", "21"] #, "22"]
        build: ["Release"] #, "Debug"] #, "RelWithDebInfo"]
        os: ["ubuntu-22.04", "ubuntu-24.04", "ubuntu-26.04"]
        exclude:
          # LLVM 20 not available for ubuntu-26.04 in apt.llvm.org
          - os: "ubuntu-26.04"
            llvm: "20"

    timeout-minutes: 30

    steps:
    - name: add llvm
      run: |
          source /etc/os-release
          sudo mkdir -p /etc/apt/keyrings
          wget https://apt.llvm.org/llvm-snapshot.gpg.key
          gpg --no-default-keyring --keyring ./temp-keyring.gpg --import llvm-snapshot.gpg.key
          sudo gpg --no-default-keyring --keyring ./temp-keyring.gpg --export --output /etc/apt/keyrings/llvm-snapshot.gpg
          rm ./temp-keyring.gpg
          sudo apt-add-repository "deb http://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME}-${{ matrix.llvm }} main" || true
          sudo sed -i 's/^deb /deb [signed-by=\/etc\/apt\/keyrings\/llvm-snapshot.gpg] /' "/etc/apt/sources.list.d/archive_uri-http_apt_llvm_org_${UBUNTU_CODENAME}_-${UBUNTU_CODENAME}.list"
          sudo apt-get update
          sudo apt-get install -y cmake gcc g++ llvm-${{ matrix.llvm }}-dev libclang-${{ matrix.llvm }}-dev clang-${{ matrix.llvm }} lld-${{ matrix.llvm }} mlir-${{ matrix.llvm }}-tools libmlir-${{ matrix.llvm }} libmlir-${{ matrix.llvm }}-dev libflang-${{ matrix.llvm }}-dev flang-${{ matrix.llvm }} libzstd-dev libmpfr-dev libomp-${{ matrix.llvm }}-dev
          sudo python3 -m pip install lit
    - uses: actions/checkout@v4
    - name: mkdir
      run: rm -rf build && mkdir build
    - name: cmake
      working-directory: build
      run: cmake ../ -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DLLVM_EXTERNAL_LIT=`which lit` -DLLVM_DIR=/usr/lib/llvm-${{ matrix.llvm }}/lib/cmake/llvm
    - name: make
      working-directory: build
      run: make -j `nproc`
    - name: make check
      working-directory: build
      run: make -j `nproc` check-all
